CREATE TABLE chat_histories
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT                              NOT NULL,
    message         TEXT                                NOT NULL,
    is_user_message BOOLEAN                             NOT NULL,
    ai_model        VARCHAR(50)                         NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_histories_users FOREIGN KEY (user_id) REFERENCES users (id)
);

alter table chat_histories
    owner to ishenaly;