create table words
(
    id         bigint generated by default as identity
        primary key,
    english    varchar(255) not null
        constraint unique_english
            unique,
    example_en varchar(255),
    example_ru varchar(255),
    russian    varchar(255) not null,
    sticker_id varchar(255),
    theme      varchar(255),
    level      varchar(255)
        constraint words_level_check
            check ((level)::text = ANY
        ((ARRAY ['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying, 'C2'::character varying])::text[]))
    );

alter table words
    owner to ishenaly;

create unique index idx_words_english_unique
    on words (upper(english::text));

create table users
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    keys             integer,
    level            varchar(255)
        constraint users_level_check
            check ((level)::text = ANY
        ((ARRAY ['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying, 'C2'::character varying])::text[])),
    telegram_chat_id bigint
        constraint uk6t9hfgo7gxvw604uq3sqkkbxq
            unique,
    username         varchar(255),
    xp               integer
);

alter table users
    owner to ishenaly;

create table quiz_results
(
    id              bigint generated by default as identity
        primary key,
    completed_at    timestamp(6) not null,
    score           integer      not null,
    total_questions integer      not null,
    user_id         bigint       not null
        constraint fkc31xkn83q9v6yf9gh2spkvxrc
            references users
            on delete cascade
);

alter table quiz_results
    owner to ishenaly;

create table subscriptions
(
    id         bigint generated by default as identity
        primary key,
    end_date   timestamp(6),
    start_date timestamp(6) not null,
    type       varchar(255) not null
        constraint subscriptions_type_check
            check ((type)::text = ANY ((ARRAY ['FREE'::character varying, 'PREMIUM'::character varying])::text[])),
    user_id    bigint       not null
        constraint fkhro52ohfqfbay9774bev0qinr
            references users
);

alter table subscriptions
    owner to ishenaly;

create table user_words
(
    id         bigint generated by default as identity
        primary key,
    learned_at timestamp(6) not null,
    user_id    bigint       not null
        constraint fknmok7ci9149qjor41u2di237k
            references users
            on delete cascade,
    word_id    bigint       not null
        constraint fk5ip5cm34fpih9occ8v38ur2l6
            references words
);

alter table user_words
    owner to ishenaly;

create table support_requests
(
    id          bigint generated by default as identity
        primary key,
    user_id     bigint       not null
        constraint fk_support_requests_users
            references users
            on delete cascade,
    username    varchar(255) not null,
    request_text text         not null,
    created_at  timestamp(6) not null
);

alter table support_requests
    owner to ishenaly;
