insert into public.tests (id, lesson_id, question, correct_option)
values  (1, 1, 'Какой цвет называется "Blue" на английском?', 'Синий'),
        (2, 1, 'Какой цвет получается при смешивании красного и жёлтого?', 'Orange'),
        (3, 1, 'Как правильно произносится цвет "Green" на английском?', '/griːn/'),
        (4, 2, 'Какое приветствие лучше использовать в 9 утра?', 'Good morning'),
        (5, 2, 'Как сказать "Привет" неформально на английском?', 'Hi'),
        (6, 2, 'Заполни пропуск: "Hey, Mike! What’s up?" — "____, just heading to the park."', 'Not much'),
        (7, 3, 'Что означает идиома "Once in a blue moon" на русском?', 'Очень редко'),
        (8, 3, 'Какую идиому использовать, если что-то очень дорого?', 'Cost an arm and a leg'),
        (9, 3, 'Заполни пропуск: "To start a conversation casually, you need to ____."', 'Break the ice');

insert into public.test_options (test_id, option)
values  (1, 'Синий'),
        (1, 'Красный'),
        (1, 'Зелёный'),
        (2, 'Orange'),
        (2, 'Green'),
        (2, 'Magenta'),
        (2, 'Purple'),
        (2, 'Brown'),
        (3, '/griːn/'),
        (3, '/ˈjɛloʊ/'),
        (4, 'Good morning'),
        (4, 'Good evening'),
        (4, 'Good afternoon'),
        (4, 'Hey'),
        (5, 'Hi'),
        (5, 'Good afternoon'),
        (5, 'Ms. Smith'),
        (6, 'Not much'),
        (6, 'Goodbye'),
        (6, 'Good morning'),
        (6, 'I’m fine'),
        (6, 'Hello'),
        (7, 'Очень редко'),
        (7, 'Попасть в точку'),
        (7, 'Быть нездоровым'),
        (8, 'Cost an arm and a leg'),
        (8, 'Break the ice'),
        (8, 'Under the weather'),
        (8, 'Hit the nail on the head'),
        (9, 'Break the ice'),
        (9, 'Feel under the weather');

