--liquibase formatted sql

--changeset Jules (AI Agent):2025-05-28--11-populate_lesson_content
--comment: Populate html_content, css_content, and javascript_content for 10 lessons

-- Lesson 1: Nature's Wonders
UPDATE lessons
SET
  html_content = '<div id=\"lesson-natures-wonders-content\"><div id=\"falling-elements-container-nature\"></div><h1>Nature''s Wonders: Cycles of Life</h1><p>Explore nature''s beauty and its cycles.</p><img src=\"placeholder_nature.png\" alt=\"Nature Cycle\"></div>',
  css_content = '#lesson-natures-wonders-content { font-family: ''Georgia'', serif; padding: 20px; background: #e6ffe6; color: #3b4f2a; border-radius: 10px; position: relative; overflow: hidden; min-height: 300px; text-align:center; } #lesson-natures-wonders-content h1 { color: #2a381c; } #falling-elements-container-nature { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; } .natural-element { position: absolute; font-size: 18px; user-select: none; opacity:0; } .natural-element.animate { animation-name: fall; animation-timing-function: linear; animation-iteration-count: 1; } @keyframes fall { 0% { transform: translateY(-20px) rotate(0deg); opacity: 0; } 10% { opacity: 1; } 90% { opacity: 1; } 100% { transform: translateY(320px) rotate(360deg); opacity: 0; } }',
  javascript_content = 'document.addEventListener(''DOMContentLoaded'', function() { const c = document.getElementById(''lesson-natures-wonders-content''); if(!c) return; const ec = c.querySelector(''#falling-elements-container-nature''); if (!ec) return; const et = [''🍂'', ''🍁'', ''🌸'', ''🌿'']; let ei; function cf() { if (!document.body.contains(c) || getComputedStyle(c).display === ''none'') { clearInterval(ei); return; } const el = document.createElement(''div''); el.className = ''natural-element''; el.textContent = et[Math.floor(Math.random() * et.length)]; el.style.left = Math.random() * 95 + ''%''; el.style.fontSize = Math.random() * 8 + 12 + ''px''; el.style.animationDuration = Math.random() * 4 + 6 + ''s''; ec.appendChild(el); el.classList.add(''animate''); el.addEventListener(''animationend'', function() { el.remove(); }); } function sa() { if (document.body.contains(c) && getComputedStyle(c).display !== ''none'') { ei = setInterval(cf, 800); } } function xa() { clearInterval(ei); } const o = new IntersectionObserver(e => e.forEach(x => x.isIntersecting ? sa() : xa()), { threshold: 0.1 }); if(c) o.observe(c); else xa(); const mo = new MutationObserver((m, ob) => { if (!document.body.contains(c)) { xa(); ob.disconnect(); } }); mo.observe(document.body, { childList: true, subtree: true }); });'
WHERE title = 'Nature''s Wonders';

-- Lesson 2: Journey Through Space
UPDATE lessons
SET
  html_content = '<div id=\"lesson-animated-bg-content\"><h1>Journey Through Space</h1><p>Explore the cosmos!</p></div>',
  css_content = '#lesson-animated-bg-content { position: relative; height: 300px; background-color: #000011; color: white; padding: 20px; text-align: center; overflow: hidden; border-radius: 10px; } #lesson-animated-bg-content h1 { text-shadow: 0 0 8px #0ff; z-index:1; position:relative; } #lesson-animated-bg-content p { z-index:1; position:relative;} #lesson-animated-bg-content::before { content: ''''; position: absolute; top: 0; left: 0; width: 200%; height: 200%; background-image: radial-gradient(circle at 20px 30px, #fff 1px, transparent 1.5px), radial-gradient(circle at 50px 80px, #eee 1px, transparent 1.5px); background-size: 150px 150px; animation: moveStars 50s linear infinite; z-index: 0; } @keyframes moveStars { from { transform: translate(0, 0); } to { transform: translate(-150px, -150px); } }',
  javascript_content = '/* CSS only animation */'
WHERE title = 'Journey Through Space';

-- Lesson 3: Mysteries of the Deep Sea
UPDATE lessons
SET
  html_content = '<div id=\"lesson-deep-sea-content\"><div id=\"bubbles-container\"></div><h1>Mysteries of the Deep Sea</h1><p>Dive into the abyss.</p><img src=\"placeholder_deep_sea.png\" alt=\"Deep Sea\"></div>',
  css_content = '#lesson-deep-sea-content { font-family: ''Verdana'', sans-serif; background: linear-gradient(to bottom, #010508, #001a29); color: #aaccff; padding: 20px; border-radius: 10px; position: relative; overflow: hidden; min-height: 300px; text-align:center;} #lesson-deep-sea-content h1 { color: #cceeff; z-index:1; position:relative;} #lesson-deep-sea-content img {z-index:1; position:relative; max-width:100px; margin-top:10px;} #bubbles-container { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; z-index: 0; } .bubble { position: absolute; background-color: rgba(173, 216, 230, 0.25); border-radius: 50%; opacity:0;} .bubble.animate {animation-name: rise; animation-timing-function: linear; animation-iteration-count: 1;} @keyframes rise { 0% { bottom: -20px; opacity: 0.7; transform: scale(0.4) translateX(0px); } 50% {transform: scale(0.6) translateX(10px);} 100% { bottom: 100%; opacity: 0; transform: scale(0.8) translateX(-10px); } }',
  javascript_content = 'document.addEventListener(''DOMContentLoaded'', function() { const c = document.getElementById(''lesson-deep-sea-content''); if(!c) return; const bc = c.querySelector(''#bubbles-container''); if (!bc) return; let bi; function cb() { if (!document.body.contains(c) || getComputedStyle(c).display === ''none'') { clearInterval(bi); return; } const b = document.createElement(''div''); b.className = ''bubble''; b.style.left = Math.random() * 90 + 5 + ''%''; const s = Math.random() * 10 + 5; b.style.width = s + ''px''; b.style.height = s + ''px''; b.style.animationDuration = Math.random() * 6 + 4 + ''s''; bc.appendChild(b); b.classList.add(''animate''); b.addEventListener(''animationend'', function() { b.remove(); }); } function sa() { if (document.body.contains(c) && getComputedStyle(c).display !== ''none'') { bi = setInterval(cb, 600); } } function xa() { clearInterval(bi); } const o = new IntersectionObserver(e => e.forEach(x => x.isIntersecting ? sa() : xa()), { threshold: 0.1 }); if(c) o.observe(c); else xa(); const mo = new MutationObserver((m, ob) => { if (!document.body.contains(c)) { xa(); ob.disconnect(); } }); mo.observe(document.body, { childList: true, subtree: true }); });'
WHERE title = 'Mysteries of the Deep Sea';

-- Lesson 4: The Magic of Colors
UPDATE lessons
SET
  html_content = '<div id=\"lesson-magic-of-colors-content\"><h1>The Magic of Colors</h1><p>Discover primary, secondary, and tertiary colors!</p><div class=\"color-palette\"><div class=\"color-box primary\" style=\"background-color:red;\">Red (P)</div><div class=\"color-box primary\" style=\"background-color:yellow; color:black;\">Yellow (P)</div><div class=\"color-box primary\" style=\"background-color:blue;\">Blue (P)</div><div class=\"color-box secondary\" style=\"background-color:orange;\">Orange (S)</div><div class=\"color-box secondary\" style=\"background-color:green;\">Green (S)</div><div class=\"color-box secondary\" style=\"background-color:purple;\">Purple (S)</div></div><button id=\"color-changer-button\">Change Palette Background</button></div>',
  css_content = '#lesson-magic-of-colors-content { font-family: Arial, sans-serif; padding: 20px; text-align:center; border-radius:10px; background-color:#f0f8ff;} #lesson-magic-of-colors-content h1 { color: #333; } #lesson-magic-of-colors-content .color-palette { display: flex; flex-wrap:wrap; justify-content: center; padding: 10px; margin: 15px 0; border-radius:5px; transition: background-color 0.5s ease;} #lesson-magic-of-colors-content .color-box { width: 100px; height: 70px; margin: 5px; display: flex; align-items: center; justify-content: center; font-weight: bold; color: white; border-radius: 5px; text-shadow: 1px 1px 1px #555;} #lesson-magic-of-colors-content button { padding: 10px 15px; margin-top:10px; border:none; background-color:#ff69b4; color:white; border-radius:5px; cursor:pointer; }',
  javascript_content = 'document.addEventListener(''DOMContentLoaded'', function() { const l = document.getElementById(''lesson-magic-of-colors-content''); if(!l) return; const b = l.querySelector(''#color-changer-button''); const p = l.querySelector(''.color-palette''); const c = [''#fff0f5'', ''#e6e6fa'', ''#f0fff0'', ''#fffacd'', ''#f5f5dc'']; let ci = 0; if(b && p) { b.addEventListener(''click'', function() { ci = (ci + 1) % c.length; p.style.backgroundColor = c[ci]; }); } });'
WHERE title = 'The Magic of Colors';

-- Lesson 5: The Art of Storytelling
UPDATE lessons
SET
  html_content = '<div id=\"lesson-storytelling-content\"><div class=\"book-layout\"><div class=\"book-left-page\"><h1>The Art of Storytelling</h1><h2>Chapter 1: The Beginning</h2><p>Every story has a beginning. It sets the scene, introduces characters, and hints at the conflict to come. Imagine a dusty old map, a mysterious letter...</p><span class=\"page-number\">1</span></div><div class=\"book-right-page\"><h2>Chapter 2: The Journey</h2><p>The middle of a story, or the ''journey'', is where characters face challenges, discover strengths, and the plot thickens. Think of winding roads and unexpected encounters.</p><div class=\"dialogue-bubble\">What''s that glowing light?</div><span class=\"page-number\">2</span></div></div></div>',
  css_content = '#lesson-storytelling-content { font-family: ''Georgia'', serif; padding: 20px; background-color: #f5e8d1; /* Parchment */ } #lesson-storytelling-content .book-layout { display: flex; max-width: 800px; margin: auto; background: #fff; box-shadow: 5px 5px 15px rgba(0,0,0,0.2); border: 1px solid #c9b79c; } #lesson-storytelling-content .book-left-page, #lesson-storytelling-content .book-right-page { padding: 30px; width: 50%; box-sizing: border-box; position:relative; min-height:300px;} #lesson-storytelling-content .book-left-page { border-right: 1px dashed #d1c0a5; } #lesson-storytelling-content h1 { font-size: 1.8em; color: #5a3e2b; text-align:center;} #lesson-storytelling-content h2 { font-size: 1.3em; color: #8c6b52; margin-top:15px; margin-bottom:10px; } #lesson-storytelling-content p { line-height: 1.6; color: #4a3b31; } .dialogue-bubble { background-color: #e0f7fa; border: 1px solid #b2ebf2; border-radius: 10px; padding: 10px; margin: 10px 0; display:inline-block; } .page-number { position:absolute; bottom:10px; right:15px; font-style:italic; color:#777;}',
  javascript_content = '/* No JavaScript for this lesson */'
WHERE title = 'The Art of Storytelling';

-- Lesson 6: Ancient Civilizations
UPDATE lessons
SET
  html_content = '<div id=\"lesson-ancient-civilizations-content\"><h1>Ancient Civilizations</h1><p>Explore mighty empires of the past.</p><div class=\"timeline\"><div class=\"event egypt\">Egypt <br/>(c. 3100 BC) <img src=\"placeholder_pyramid.png\" alt=\"Pyramid\"></div><div class=\"event rome\">Rome <br/>(c. 753 BC) <img src=\"placeholder_colosseum.png\" alt=\"Colosseum\"></div><div class=\"event maya\">Maya <br/>(c. 2000 BC) <img src=\"placeholder_mayan_temple.png\" alt=\"Mayan Temple\"></div></div><div class=\"papyrus-note\">Their legacies live on in stone and story.</div></div>',
  css_content = '#lesson-ancient-civilizations-content { font-family: ''Trajan Pro'', ''Palatino Linotype'', serif; padding: 20px; background-color: #f0e6c8; text-align:center;} #lesson-ancient-civilizations-content h1 { color: #5d4037; } #lesson-ancient-civilizations-content .timeline { display: flex; justify-content: space-around; margin: 20px 0; padding:10px; background-image:url(''placeholder_scroll_texture.png''); background-color:#e6d9b3; border:1px solid #c8b080;} #lesson-ancient-civilizations-content .event { width: 120px; padding: 10px; text-align: center; border: 1px solid #bca070; background-color: #fff8e1; margin:5px; box-shadow: 2px 2px 5px #aaa;} #lesson-ancient-civilizations-content .event img { width:80px; height:60px; margin-top:5px; background-color:#ccc; border:1px solid #999;} #lesson-ancient-civilizations-content .papyrus-note { background-color: #fffaf0; border: 1px solid #dcd0b8; padding: 10px; margin-top: 20px; display:inline-block; font-style:italic; color:#6b4f31;}',
  javascript_content = '/* No JavaScript for this lesson */'
WHERE title = 'Ancient Civilizations';

-- Lesson 7: The World of Music
UPDATE lessons
SET
  html_content = '<div id=\"lesson-world-of-music-content\"><h1>The World of Music</h1><p>From classical symphonies to modern beats.</p><div class=\"genre-container\"><div class=\"genre-card\" id=\"classical\">Classical <img src=\"placeholder_violin_ico.png\"></div><div class=\"genre-card\" id=\"jazz\">Jazz <img src=\"placeholder_sax_ico.png\"></div><div class=\"genre-card\" id=\"rock\">Rock <img src=\"placeholder_guitar_ico.png\"></div></div><div id=\"music-staff-bg\"><span class=\"note\">&#9835;</span> <span class=\"note g-clef\">&#119070;</span> <span class=\"note\">&#9833;</span></div></div>',
  css_content = '#lesson-world-of-music-content { font-family: ''Helvetica Neue'', sans-serif; padding: 20px; background-color:#f0f0f0; text-align:center; border-radius:10px;} #lesson-world-of-music-content h1 { color: #333; } #lesson-world-of-music-content .genre-container { display: flex; justify-content: space-evenly; margin: 20px 0; } #lesson-world-of-music-content .genre-card { padding: 15px; border: 1px solid #ccc; border-radius: 8px; width: 100px; cursor:pointer; background-color:white; transition: transform 0.2s; } #lesson-world-of-music-content .genre-card:hover {transform: scale(1.05); background-color:#e9e9e9;} #lesson-world-of-music-content .genre-card img {width:40px; height:40px; display:block; margin:5px auto; background-color:#ddd;} #lesson-world-of-music-content #music-staff-bg { background-image: repeating-linear-gradient(#ccc 0px, #ccc 1px, transparent 1px, transparent 10px); height:50px; margin-top:30px; padding-top:5px; border-top:1px solid #aaa; border-bottom:1px solid #aaa;} #lesson-world-of-music-content .note { font-size:2.5em; margin: 0 10px; color:#444;} #lesson-world-of-music-content .g-clef {font-size:3.5em;}',
  javascript_content = '/* No JavaScript for this lesson */'
WHERE title = 'The World of Music';

-- Lesson 8: Poetry in Motion
UPDATE lessons
SET
  html_content = '<div id=\"lesson-poetry-in-motion-content\"><div class=\"poem-container\"><h1>Poetry in Motion</h1><blockquote class=\"poem-stanza\">The woods are lovely, dark and deep,<br>But I have promises to keep,<br>And miles to go before I sleep,<br>And miles to go before I sleep.</blockquote><cite>- Robert Frost (Stopping by Woods on a Snowy Evening)</cite></div><div class=\"feather-pen-placeholder\"><img src=\"placeholder_quill_pen.png\" alt=\"Quill Pen\"></div></div>',
  css_content = '#lesson-poetry-in-motion-content { font-family: ''Garamond'', ''Times New Roman'', serif; padding: 30px; background-color: #fdfcf9; color: #333; display:flex; align-items:center; justify-content:center; min-height:300px; text-align:left;} #lesson-poetry-in-motion-content .poem-container { max-width:500px; } #lesson-poetry-in-motion-content h1 { font-family: ''Brush Script MT'', cursive; font-size: 2.8em; color: #5a4a3a; margin-bottom: 20px; text-align:center;} #lesson-poetry-in-motion-content .poem-stanza { font-size: 1.3em; line-height: 1.8; margin: 0; padding: 15px; border-left: 3px solid #a08c78; background-color: #f9f5f0; color: #4a3f35; transition: background-color 0.3s;} #lesson-poetry-in-motion-content .poem-stanza:hover { background-color: #f4efe7; } #lesson-poetry-in-motion-content cite { display: block; text-align: right; margin-top: 15px; font-style: italic; color: #7a6a5a; } #lesson-poetry-in-motion-content .feather-pen-placeholder img {width:80px; margin-left:30px; opacity:0.6; background-color:#eee;}',
  javascript_content = '/* No JavaScript for this lesson */'
WHERE title = 'Poetry in Motion';

-- Lesson 9: The Power of Dreams
UPDATE lessons
SET
  html_content = '<div id=\"lesson-power-of-dreams-content\"><div class=\"dreamscape-background\"></div><h1>The Power of Dreams</h1><p>Journey into the subconscious mind.</p><div class=\"dream-symbol\"><img src=\"placeholder_flying_dream.png\" alt=\"Flying Symbol\"><span>Flying - Freedom, escape</span></div><div class=\"dream-symbol\"><img src=\"placeholder_falling_dream.png\" alt=\"Falling Symbol\"><span>Falling - Insecurity, loss of control</span></div></div>',
  css_content = '#lesson-power-of-dreams-content { font-family: ''Arial'', sans-serif; padding: 20px; color: white; text-align: center; position: relative; overflow: hidden; min-height:300px; border-radius:10px;} #lesson-power-of-dreams-content .dreamscape-background { position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: linear-gradient(45deg, #23074d, #cc5333, #2c3e50, #bdc3c7); background-size: 400% 400%; animation: dreamShift 20s ease infinite; z-index: -1; } @keyframes dreamShift { 0%{background-position:0% 50%} 50%{background-position:100% 50%} 100%{background-position:0% 50%} } #lesson-power-of-dreams-content h1 { text-shadow: 0 0 10px rgba(0,0,0,0.5); font-size:2.2em;} #lesson-power-of-dreams-content p {margin-bottom:20px;} #lesson-power-of-dreams-content .dream-symbol { display: inline-block; margin: 10px; padding:10px; background-color: rgba(255,255,255,0.1); border-radius: 5px; } #lesson-power-of-dreams-content .dream-symbol img { width: 80px; height: 60px; display:block; margin:auto; background-color:#555; border-radius:4px;} #lesson-power-of-dreams-content .dream-symbol span {font-size:0.9em; display:block; margin-top:5px;}',
  javascript_content = '/* No JavaScript for this lesson */'
WHERE title = 'The Power of Dreams';

-- Lesson 10: Adventures in Cooking
UPDATE lessons
SET
  html_content = '<div id=\"lesson-adventures-in-cooking-content\"><div class=\"recipe-card-layout\"><h1>My Favorite Smoothie</h1><img class=\"food-image-placeholder\" src=\"placeholder_smoothie.png\" alt=\"Smoothie\"><h2>Ingredients:</h2><ul><li>1 Banana</li><li>1/2 cup Berries</li><li>1/4 cup Yogurt</li><li>1/2 cup Milk/Juice</li></ul><h2>Steps:</h2><ol><li>Combine all ingredients in a blender.</li><li>Blend until smooth.</li><li>Pour into a glass and enjoy!</li></ol><p class=\"tip\">Tip: Add spinach for extra nutrients!</p></div></div>',
  css_content = '#lesson-adventures-in-cooking-content { font-family: ''Comic Sans MS'', ''Chalkboard SE'', sans-serif; padding: 20px; background-color: #fff7e6; text-align:left; border-radius:10px;} #lesson-adventures-in-cooking-content .recipe-card-layout { max-width: 450px; margin: auto; padding: 25px; background-color: #ffffff; border: 2px dashed #ffcc80; border-radius: 15px; box-shadow: 0 3px 10px rgba(200,100,0,0.1); } #lesson-adventures-in-cooking-content h1 { color: #ff6f00; text-align:center; font-size:1.8em;} #lesson-adventures-in-cooking-content h2 { color: #ff8f00; font-size:1.3em; margin-top:15px;} #lesson-adventures-in-cooking-content .food-image-placeholder { display:block; width:80%; max-width:200px; height:auto; margin:10px auto; border-radius:10px; background-color:#eee; border:1px solid #ddd;} #lesson-adventures-in-cooking-content ul, #lesson-adventures-in-cooking-content ol { margin-left:20px; padding-left:15px;} #lesson-adventures-in-cooking-content li { margin-bottom:5px; } #lesson-adventures-in-cooking-content .tip { background-color:#fffde7; border:1px solid #fff59d; padding:10px; border-radius:5px; margin-top:15px; font-size:0.95em; text-align:center;}',
  javascript_content = '/* No JavaScript for this lesson */'
WHERE title = 'Adventures in Cooking';

--rollback Clarification: Rollback for this changeset would ideally involve setting html_content, css_content, and javascript_content back to their previous states (e.g., 'Content coming soon...').
--rollback However, without knowing the exact previous state for each lesson, a simple approach is to set them to NULL or a placeholder.
--rollback For simplicity in this automated context, we'll assume a placeholder is sufficient if rollback is ever manually invoked.
--rollback UPDATE lessons SET html_content = ''Placeholder content after rollback'', css_content = ''/* Placeholder CSS after rollback */'', javascript_content = ''/* Placeholder JS after rollback */'' WHERE title IN ('Nature''s Wonders', 'Journey Through Space', 'Mysteries of the Deep Sea', 'The Magic of Colors', 'The Art of Storytelling', 'Ancient Civilizations', 'The World of Music', 'Poetry in Motion', 'The Power of Dreams', 'Adventures in Cooking');
